<?php
use Entities\Pokemon as PokemonEntity;

class DatabaseSeeder extends Seeder {

    protected $pokemon = array(
        array('id' => '1', 'name' => 'Bulbasaur'),
        array('id' => '2', 'name' => 'Ivysaur'),
        array('id' => '3', 'name' => 'Venusaur'),
        array('id' => '4', 'name' => 'Charmander'),
        array('id' => '5', 'name' => 'Charmeleon'),
        array('id' => '6', 'name' => 'Charizard'),
        array('id' => '7', 'name' => 'Squirtle'),
        array('id' => '8', 'name' => 'Wartortle'),
        array('id' => '9', 'name' => 'Blastoise'),
        array('id' => '10', 'name' => 'Caterpie'),
        array('id' => '11', 'name' => 'Metapod'),
        array('id' => '12', 'name' => 'Butterfree'),
        array('id' => '13', 'name' => 'Weedle'),
        array('id' => '14', 'name' => 'Kakuna'),
        array('id' => '15', 'name' => 'Beedrill'),
        array('id' => '16', 'name' => 'Pidgey'),
        array('id' => '17', 'name' => 'Pidgeotto'),
        array('id' => '18', 'name' => 'Pidgeot'),
        array('id' => '19', 'name' => 'Rattata'),
        array('id' => '20', 'name' => 'Raticate'),
        array('id' => '21', 'name' => 'Spearow'),
        array('id' => '22', 'name' => 'Fearow'),
        array('id' => '23', 'name' => 'Ekans'),
        array('id' => '24', 'name' => 'Arbok'),
        array('id' => '25', 'name' => 'Pikachu'),
        array('id' => '26', 'name' => 'Raichu'),
        array('id' => '27', 'name' => 'Sandshrew'),
        array('id' => '28', 'name' => 'Sandslash'),
        array('id' => '29', 'name' => 'Nidoran'),
        array('id' => '30', 'name' => 'Nidorina'),
        array('id' => '31', 'name' => 'Nidoqueen'),
        array('id' => '32', 'name' => 'Nidoran'),
        array('id' => '33', 'name' => 'Nidorino'),
        array('id' => '34', 'name' => 'Nidoking'),
        array('id' => '35', 'name' => 'Clefairy'),
        array('id' => '36', 'name' => 'Clefable'),
        array('id' => '37', 'name' => 'Vulpix'),
        array('id' => '38', 'name' => 'Ninetales'),
        array('id' => '39', 'name' => 'Jigglypuff'),
        array('id' => '40', 'name' => 'Wigglytuff'),
        array('id' => '41', 'name' => 'Zubat'),
        array('id' => '42', 'name' => 'Golbat'),
        array('id' => '43', 'name' => 'Oddish'),
        array('id' => '44', 'name' => 'Gloom'),
        array('id' => '45', 'name' => 'Vileplume'),
        array('id' => '46', 'name' => 'Paras'),
        array('id' => '47', 'name' => 'Parasect'),
        array('id' => '48', 'name' => 'Venonat'),
        array('id' => '49', 'name' => 'Venomoth'),
        array('id' => '50', 'name' => 'Diglett'),
        array('id' => '51', 'name' => 'Dugtrio'),
        array('id' => '52', 'name' => 'Meowth'),
        array('id' => '53', 'name' => 'Persian'),
        array('id' => '54', 'name' => 'Psyduck'),
        array('id' => '55', 'name' => 'Golduck'),
        array('id' => '56', 'name' => 'Mankey'),
        array('id' => '57', 'name' => 'Primeape'),
        array('id' => '58', 'name' => 'Growlithe'),
        array('id' => '59', 'name' => 'Arcanine'),
        array('id' => '60', 'name' => 'Poliwag'),
        array('id' => '61', 'name' => 'Poliwhirl'),
        array('id' => '62', 'name' => 'Poliwrath'),
        array('id' => '63', 'name' => 'Abra'),
        array('id' => '64', 'name' => 'Kadabra'),
        array('id' => '65', 'name' => 'Alakazam'),
        array('id' => '66', 'name' => 'Machop'),
        array('id' => '67', 'name' => 'Machoke'),
        array('id' => '68', 'name' => 'Machamp'),
        array('id' => '69', 'name' => 'Bellsprout'),
        array('id' => '70', 'name' => 'Weepinbell'),
        array('id' => '71', 'name' => 'Victreebel'),
        array('id' => '72', 'name' => 'Tentacool'),
        array('id' => '73', 'name' => 'Tentacruel'),
        array('id' => '74', 'name' => 'Geodude'),
        array('id' => '75', 'name' => 'Graveler'),
        array('id' => '76', 'name' => 'Golem'),
        array('id' => '77', 'name' => 'Ponyta'),
        array('id' => '78', 'name' => 'Rapidash'),
        array('id' => '79', 'name' => 'Slowpoke'),
        array('id' => '80', 'name' => 'Slowbro'),
        array('id' => '81', 'name' => 'Magnemite'),
        array('id' => '82', 'name' => 'Magneton'),
        array('id' => '83', 'name' => 'Farfetch'),
        array('id' => '84', 'name' => 'Doduo'),
        array('id' => '85', 'name' => 'Dodrio'),
        array('id' => '86', 'name' => 'Seel'),
        array('id' => '87', 'name' => 'Dewgong'),
        array('id' => '88', 'name' => 'Grimer'),
        array('id' => '89', 'name' => 'Muk'),
        array('id' => '90', 'name' => 'Shellder'),
        array('id' => '91', 'name' => 'Cloyster'),
        array('id' => '92', 'name' => 'Gastly'),
        array('id' => '93', 'name' => 'Haunter'),
        array('id' => '94', 'name' => 'Gengar'),
        array('id' => '95', 'name' => 'Onix'),
        array('id' => '96', 'name' => 'Drowzee'),
        array('id' => '97', 'name' => 'Hypno'),
        array('id' => '98', 'name' => 'Krabby'),
        array('id' => '99', 'name' => 'Kingler'),
        array('id' => '100', 'name' => 'Voltorb'),
        array('id' => '101', 'name' => 'Electrode'),
        array('id' => '102', 'name' => 'Exeggcute'),
        array('id' => '103', 'name' => 'Exeggutor'),
        array('id' => '104', 'name' => 'Cubone'),
        array('id' => '105', 'name' => 'Marowak'),
        array('id' => '106', 'name' => 'Hitmonlee'),
        array('id' => '107', 'name' => 'Hitmonchan'),
        array('id' => '108', 'name' => 'Lickitung'),
        array('id' => '109', 'name' => 'Koffing'),
        array('id' => '110', 'name' => 'Weezing'),
        array('id' => '111', 'name' => 'Rhyhorn'),
        array('id' => '112', 'name' => 'Rhydon'),
        array('id' => '113', 'name' => 'Chansey'),
        array('id' => '114', 'name' => 'Tangela'),
        array('id' => '115', 'name' => 'Kangaskhan'),
        array('id' => '116', 'name' => 'Horsea'),
        array('id' => '117', 'name' => 'Seadra'),
        array('id' => '118', 'name' => 'Goldeen'),
        array('id' => '119', 'name' => 'Seaking'),
        array('id' => '120', 'name' => 'Staryu'),
        array('id' => '121', 'name' => 'Starmie'),
        array('id' => '122', 'name' => 'Mr. Mime'),
        array('id' => '123', 'name' => 'Scyther'),
        array('id' => '124', 'name' => 'Jynx'),
        array('id' => '125', 'name' => 'Electabuzz'),
        array('id' => '126', 'name' => 'Magmar'),
        array('id' => '127', 'name' => 'Pinsir'),
        array('id' => '128', 'name' => 'Tauros'),
        array('id' => '129', 'name' => 'Magikarp'),
        array('id' => '130', 'name' => 'Gyarados'),
        array('id' => '131', 'name' => 'Lapras'),
        array('id' => '132', 'name' => 'Ditto'),
        array('id' => '133', 'name' => 'Eevee'),
        array('id' => '134', 'name' => 'Vaporeon'),
        array('id' => '135', 'name' => 'Jolteon'),
        array('id' => '136', 'name' => 'Flareon'),
        array('id' => '137', 'name' => 'Porygon'),
        array('id' => '138', 'name' => 'Omanyte'),
        array('id' => '139', 'name' => 'Omastar'),
        array('id' => '140', 'name' => 'Kabuto'),
        array('id' => '141', 'name' => 'Kabutops'),
        array('id' => '142', 'name' => 'Aerodactyl'),
        array('id' => '143', 'name' => 'Snorlax'),
        array('id' => '144', 'name' => 'Articuno'),
        array('id' => '145', 'name' => 'Zapdos'),
        array('id' => '146', 'name' => 'Moltres'),
        array('id' => '147', 'name' => 'Dratini'),
        array('id' => '148', 'name' => 'Dragonair'),
        array('id' => '149', 'name' => 'Dragonite'),
        array('id' => '150', 'name' => 'Mewtwo'),
        array('id' => '151', 'name' => 'Mew'),
    );
	/**
	 * Run the database seeds.
	 *
	 * @return void
	 */
	public function run()
	{
		Eloquent::unguard();

		// $this->call('UserTableSeeder');
        foreach ($this->pokemon as $pokemon)
        {
            PokemonEntity::create($pokemon);
        }
	}

}